name: Backend CI/CD Pipeline

on:
  push:
    branches: [ main, master, wathek ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B -Dfile.encoding=UTF-8 -Dmaven.resources.filtering=false clean package

      # Pas d'étape d'upload d'artefact pour l'instant