name: Backend CI/CD Pipeline

on:
  push:
    branches: [ main, master, wathek ]
    paths:
      - '**/*.java'
      - 'pom.xml'
      - '.github/workflows/backend-ci-cd.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - '**/*.java'
      - 'pom.xml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Run tests
      run: mvn test
    
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v3
      with:
        name: backend-jar
        path: target/*.jar
        retention-days: 5