name: Backend CI/CD Pipeline

on:
  push:
    branches: [ main, master, wathek ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn -B -Dfile.encoding=UTF-8 -Dmaven.resources.filtering=false clean package
